name: wl-pprint-console
version: 0.0.1.1
description: Wadler/Leijen pretty printer with support for annotations and colorful console output. Additional useful display routines are provided, e.g, for HTML output.
synopsis: Wadler/Leijen pretty printer supporting colorful console output.
category: Text
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2016 Daniel Mendler
license: MIT
github: minad/wl-pprint-console

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1

ghc-options:
- -Wall

dependencies:
- base                >= 4.8 && < 5
- console-style       >= 0.0.1.2 && < 0.1
- wl-pprint-annotated >= 0.0.1.2 && < 0.1
- mtl                 >= 2.2 && < 2.4
- text                >= 0.11 && < 1.3

library:
  source-dirs: src
