name: wl-pprint-console
version: 0.1.0.1
description: Wadler/Leijen pretty printer with support for annotations and colorful console output. Additional useful display routines are provided, e.g, for HTML output.
synopsis: Wadler/Leijen pretty printer supporting colorful console output.
category: Text
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2017 Daniel Mendler
license: MIT
github: minad/wl-pprint-console

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1,
  GHC == 8.2.1,
  GHC == 8.4.3,
  GHC == 8.6.1

ghc-options:
- -Wall

dependencies:
- base                >= 4.8 && < 5
- colorful-monoids    >= 0.2 && < 0.3
- wl-pprint-annotated >= 0.0.1.2 && < 0.2
- text                >= 0.11 && < 1.3
- bytestring          >= 0.10.2 && < 0.11

library:
  source-dirs: src
